"""Add potential_locations table

Revision ID: 7e3138add69b
Revises: 9f9859268411
Create Date: 2025-09-11 17:00:44.914946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3138add69b'
down_revision = '9f9859268411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('sunlight_exposure', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('dist_to_water_source', sa.Float(), nullable=False),
    sa.Column('dist_to_flowering_area', sa.Float(), nullable=False),
    sa.Column('dist_to_feeding_station', sa.Float(), nullable=False),
    sa.Column('honey_production', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potential_locations')
    # ### end Alembic commands ###
